string name # the object's name
bool display_name # whether or not to display the object's name in the interface
geometry_msgs/PolygonStamped polygon # the polygon
std_msgs/ColorRGBA color # the polygon's color
---
