string id                            # the object's unique id
string label                         # optional text to draw in the object
geometry_msgs/PolygonStamped polygon # the polygon
geometry_msgs/Polygon text_rect      # rectangle to draw the label in
std_msgs/ColorRGBA color             # the polygon's color
---
